(lang dune 3.10)

(generate_opam_files true)

(source
 (github andreypopp/react_of_ocaml))

(authors "Andrey Popp")

(maintainers "Andrey Popp")

(license LICENSE)

(package
 (name persistent)
 (depends
  (ocaml
   (>= 5.1))
  dune
  ppxlib
  sqlite3
  ppx_deriving_schema
  containers))
