let browser_only_prop = function
  | "ref" -> true
  | "onCopy" -> true
  | "onCut" -> true
  | "onPaste" -> true
  | "onCompositionEnd" -> true
  | "onCompositionStart" -> true
  | "onCompositionUpdate" -> true
  | "onKeyDown" -> true
  | "onKeyPress" -> true
  | "onKeyUp" -> true
  | "onFocus" -> true
  | "onBlur" -> true
  | "onChange" -> true
  | "onInput" -> true
  | "onSubmit" -> true
  | "onInvalid" -> true
  | "onClick" -> true
  | "onContextMenu" -> true
  | "onDoubleClick" -> true
  | "onDrag" -> true
  | "onDragEnd" -> true
  | "onDragEnter" -> true
  | "onDragExit" -> true
  | "onDragLeave" -> true
  | "onDragOver" -> true
  | "onDragStart" -> true
  | "onDrop" -> true
  | "onMouseDown" -> true
  | "onMouseEnter" -> true
  | "onMouseLeave" -> true
  | "onMouseMove" -> true
  | "onMouseOut" -> true
  | "onMouseOver" -> true
  | "onMouseUp" -> true
  | "onSelect" -> true
  | "onTouchCancel" -> true
  | "onTouchEnd" -> true
  | "onTouchMove" -> true
  | "onTouchStart" -> true
  | "onPointerOver" -> true
  | "onPointerEnter" -> true
  | "onPointerDown" -> true
  | "onPointerMove" -> true
  | "onPointerUp" -> true
  | "onPointerCancel" -> true
  | "onPointerOut" -> true
  | "onPointerLeave" -> true
  | "onGotPointerCapture" -> true
  | "onLostPointerCapture" -> true
  | "onScroll" -> true
  | "onWheel" -> true
  | "onAbort" -> true
  | "onCanPlay" -> true
  | "onCanPlayThrough" -> true
  | "onDurationChange" -> true
  | "onEmptied" -> true
  | "onEncrypetd" -> true
  | "onEnded" -> true
  | "onError" -> true
  | "onLoadedData" -> true
  | "onLoadedMetadata" -> true
  | "onLoadStart" -> true
  | "onPause" -> true
  | "onPlay" -> true
  | "onPlaying" -> true
  | "onProgress" -> true
  | "onRateChange" -> true
  | "onSeeked" -> true
  | "onSeeking" -> true
  | "onStalled" -> true
  | "onSuspend" -> true
  | "onTimeUpdate" -> true
  | "onVolumeChange" -> true
  | "onWaiting" -> true
  | "onLoad" -> true
  | "onAnimationStart" -> true
  | "onAnimationEnd" -> true
  | "onAnimationIteration" -> true
  | "onTransitionEnd" -> true
  | _ -> false

let is_html = function
  | "a" -> true
  | "abbr" -> true
  | "address" -> true
  | "area" -> true
  | "article" -> true
  | "aside" -> true
  | "audio" -> true
  | "b" -> true
  | "base" -> true
  | "bdi" -> true
  | "bdo" -> true
  | "blockquote" -> true
  | "body" -> true
  | "br" -> true
  | "button" -> true
  | "canvas" -> true
  | "caption" -> true
  | "cite" -> true
  | "code" -> true
  | "col" -> true
  | "colgroup" -> true
  | "data" -> true
  | "datalist" -> true
  | "dd" -> true
  | "del" -> true
  | "details" -> true
  | "dfn" -> true
  | "dialog" -> true
  | "div" -> true
  | "dl" -> true
  | "dt" -> true
  | "em" -> true
  | "embed" -> true
  | "fieldset" -> true
  | "figcaption" -> true
  | "figure" -> true
  | "footer" -> true
  | "form" -> true
  | "h1" -> true
  | "h2" -> true
  | "h3" -> true
  | "h4" -> true
  | "h5" -> true
  | "h6" -> true
  | "head" -> true
  | "header" -> true
  | "hgroup" -> true
  | "hr" -> true
  | "html" -> true
  | "i" -> true
  | "iframe" -> true
  | "img" -> true
  | "input" -> true
  | "ins" -> true
  | "kbd" -> true
  | "label" -> true
  | "legend" -> true
  | "li" -> true
  | "link" -> true
  | "main" -> true
  | "map" -> true
  | "mark" -> true
  | "math" -> true
  | "menu" -> true
  | "menuitem" -> true
  | "meta" -> true
  | "meter" -> true
  | "nav" -> true
  | "noscript" -> true
  | "object" -> true
  | "ol" -> true
  | "optgroup" -> true
  | "option" -> true
  | "output" -> true
  | "p" -> true
  | "param" -> true
  | "picture" -> true
  | "pre" -> true
  | "progress" -> true
  | "q" -> true
  | "rb" -> true
  | "rp" -> true
  | "rt" -> true
  | "rtc" -> true
  | "ruby" -> true
  | "s" -> true
  | "samp" -> true
  | "script" -> true
  | "search" -> true
  | "section" -> true
  | "select" -> true
  | "slot" -> true
  | "small" -> true
  | "source" -> true
  | "span" -> true
  | "strong" -> true
  | "style" -> true
  | "sub" -> true
  | "summary" -> true
  | "sup" -> true
  | "svg" -> true
  | "table" -> true
  | "tbody" -> true
  | "td" -> true
  | "template" -> true
  | "textarea" -> true
  | "tfoot" -> true
  | "th" -> true
  | "thead" -> true
  | "time" -> true
  | "title" -> true
  | "tr" -> true
  | "track" -> true
  | "u" -> true
  | "ul" -> true
  | "var" -> true
  | "video" -> true
  | "wbr" -> true
  | _ -> false
